const fs = require("fs");
const orig = fs.readFileSync("server/index.ts", "utf8");
fs.writeFileSync("server/index.ts.final-backup", orig);
console.log("Backup saved");

const L = [];
L.push('import express, { type Request, Response, NextFunction } from "express";');
L.push('import helmet from "helmet";');
L.push('import { registerRoutes } from "./routes";');
L.push('import { serveStatic } from "./static";');
L.push('import { createServer } from "http";');
L.push('import { storage } from "./storage";');
L.push('import bcrypt from "bcryptjs";');
L.push('import { db } from "./db";');
L.push('import { sql } from "drizzle-orm";');
L.push('import { startCronJobs } from "./cron-jobs";');
L.push('import { initSocket } from "./socket";');
L.push('import { config } from "./config";');
L.push('import { startAISStream } from "./ais-stream";');
L.push('import path from "path";');
L.push('import fsNode from "fs";');
L.push('');
L.push('const app = express();');
L.push('const httpServer = createServer(app);');
L.push('initSocket(httpServer);');
L.push('');
L.push('app.use(helmet({');
L.push('  contentSecurityPolicy: {');
L.push('    directives: {');
L.push("      defaultSrc: [\"'self'\"],");
L.push("      scriptSrc: [\"'self'\", \"'unsafe-inline'\", \"'unsafe-eval'\", \"https://replit-cdn.com\", \"https://static.cloudflareinsights.com\"],");
L.push("      styleSrc: [\"'self'\", \"'unsafe-inline'\"],");
L.push("      imgSrc: [\"'self'\", \"data:\", \"blob:\", \"https:\", \"https://tiles.openseamap.org\"],");
L.push("      connectSrc: [\"'self'\", \"ws:\", \"wss:\", \"https://stream.aisstream.io\", \"https://evds2.tcmb.gov.tr\", \"https://api.zylalabs.com\", \"https://api.resend.com\", \"https://api.mapbox.com\", \"https://events.mapbox.com\", \"https://*.tiles.mapbox.com\", \"https://marine-api.open-meteo.com\", \"https://api.open-meteo.com\", \"https://tiles.openseamap.org\", \"https://nominatim.openstreetmap.org\", \"https://ofac.treasury.gov\", \"https://query1.finance.yahoo.com\", \"https://query2.finance.yahoo.com\", \"https://static.cloudflareinsights.com\"],");
L.push("      workerSrc: [\"'self'\", \"blob:\"],");
L.push("      fontSrc: [\"'self'\", \"data:\", \"https://fonts.gstatic.com\", \"https://fonts.googleapis.com\"],");
L.push("      frameAncestors: [\"'none'\"],");
L.push("      objectSrc: [\"'none'\"],");
L.push('    },');
L.push('  },');
L.push('  crossOriginEmbedderPolicy: false,');
L.push('}));');
L.push('');
L.push('declare module "http" { interface IncomingMessage { rawBody: unknown; } }');
L.push('');
L.push('if (config.NODE_ENV === "production") {');
L.push('  app.use((req: Request, res: Response, next: NextFunction) => {');
L.push('    if (req.hostname.startsWith("www.")) {');
L.push('      const nonWwwHost = req.hostname.slice(4);');
L.push('      return res.redirect(301, "https://" + nonWwwHost + req.originalUrl);');
L.push('    }');
L.push('    next();');
L.push('  });');
L.push('}');
L.push('');
L.push('app.use(express.json({ limit: "10mb", verify: (req, _res, buf) => { req.rawBody = buf; } }));');
L.push('app.use(express.urlencoded({ extended: false }));');
L.push('');
L.push('async function seedTestAdmin() {');
L.push('  const E = "test_admin@vpda.test";');
L.push('  try {');
L.push('    const existing = await db.execute(sql`SELECT id FROM users WHERE email = ${E} LIMIT 1`);');
L.push('    const rows: any[] = (existing as any).rows ?? (existing as any);');
L.push('    if (rows.length > 0) { console.log("[seed] Admin exists"); return; }');
L.push('    const h = await bcrypt.hash("TestPass123!", 12);');
L.push("    await db.execute(sql`INSERT INTO users (id, email, password_hash, first_name, last_name, user_role, active_role, email_verified, role_confirmed, is_suspended) VALUES (gen_random_uuid(), ${E}, ${h}, 'Test', 'Admin', 'admin', 'admin', true, true, false)`);");
L.push('    console.log("[seed] Admin ready");');
L.push('  } catch (err) { console.error("[seed] Admin error:", err); }');
L.push('}');
L.push('');
L.push('async function seedBunkerPrices() {');
L.push('  const existing = await storage.getBunkerPrices();');
L.push('  if (existing.length > 0) return;');
L.push('  const S = [');
L.push('    { portName: "Istanbul", portCode: "TRIST", region: "TR", ifo380: 410, vlsfo: 545, mgo: 715 },');
L.push('    { portName: "Mersin", portCode: "TRMER", region: "TR", ifo380: 405, vlsfo: 540, mgo: 710 },');
L.push('    { portName: "Izmir", portCode: "TRIZM", region: "TR", ifo380: 408, vlsfo: 543, mgo: 712 },');
L.push('    { portName: "Rotterdam", portCode: "NLRTM", region: "EU", ifo380: 395, vlsfo: 520, mgo: 700 },');
L.push('    { portName: "Singapore", portCode: "SGSIN", region: "ASIA", ifo380: 400, vlsfo: 530, mgo: 695 },');
L.push('    { portName: "Fujairah", portCode: "AEFUJ", region: "ME", ifo380: 415, vlsfo: 550, mgo: 720 },');
L.push('    { portName: "Houston", portCode: "USHOU", region: "US", ifo380: 420, vlsfo: 555, mgo: 725 },');
L.push('  ];');
L.push('  for (const r of S) { await storage.upsertBunkerPrice(r); }');
L.push('  console.log("Bunker seeded");');
L.push('}');
L.push('');
L.push('export function log(message: string, source = "express") {');
L.push('  const t = new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", second: "2-digit", hour12: true });');
L.push('  console.log(t + " [" + source + "] " + message);');
L.push('}');
L.push('');
L.push('app.use((req, res, next) => {');
L.push('  const start = Date.now();');
L.push('  const rp = req.path;');
L.push('  let captured: Record<string, any> | undefined;');
L.push('  const orig = res.json;');
L.push('  res.json = function(body, ...args) { captured = body; return orig.apply(res, [body, ...args]); };');
L.push('  res.on("finish", () => { const d = Date.now() - start; if (rp.startsWith("/api")) { let line = req.method + " " + rp + " " + res.statusCode + " in " + d + "ms"; if (captured) line += " :: " + JSON.stringify(captured); log(line); } });');
L.push('  next();');
L.push('});');
L.push('');
L.push('app.get("/api/health", (_req, res) => { res.status(200).json({ status: "ok" }); });');
L.push('');
L.push('app.get("/", (_req, res) => {');
L.push('  const idx = path.resolve(process.cwd(), "dist", "client", "index.html");');
L.push('  if (fsNode.existsSync(idx)) return res.sendFile(idx);');
L.push('  res.status(200).send("<!DOCTYPE html><html><body><h1>VesselPDA Running</h1></body></html>");');
L.push('});');
L.push('');
L.push('const port = config.PORT;');
L.push('httpServer.listen({ port, host: "0.0.0.0", reusePort: true }, () => {');
L.push('  console.log("Server is ready and listening on port " + port);');
L.push('});');
L.push('');
L.push('(async () => {');
L.push('  try { await registerRoutes(httpServer, app); console.log("[boot] Routes OK"); } catch (e) { console.error("[boot] Routes fail:", e); }');
L.push('  app.use((err: any, _req: Request, res: Response, next: NextFunction) => { const s = err.status || 500; if (res.headersSent) return next(err); return res.status(s).json({ message: err.message || "Error" }); });');
L.push('  if (config.NODE_ENV === "production") { try { serveStatic(app); console.log("[boot] Static OK"); } catch (e) { console.error("[boot] Static fail:", e); } }');
L.push('  else { try { const { setupVite } = await import("./vite"); await setupVite(httpServer, app); } catch (e) { console.error("[boot] Vite fail:", e); } }');
L.push('  console.log("[boot] Core ready");');
L.push('  setTimeout(() => { try { import("./seed").then(({ seedDatabase, seedForumCategories, seedPortCoordinates }) => { seedDatabase().catch(console.error); seedForumCategories().catch(console.error); seedPortCoordinates().catch(console.error); }); seedBunkerPrices().catch(console.error); seedTestAdmin().catch(console.error); import("./seed-templates").then(({ seedDocumentTemplates }) => seedDocumentTemplates().catch(console.error)); import("./seed-tariffs").then(({ seedTariffData, ensureNewTariffTables }) => ensureNewTariffTables().then(() => seedTariffData()).catch(console.error)); import("./migrate-port-calls").then(({ ensurePortCallsSchema }) => ensurePortCallsSchema().catch(console.error)); import("./migrate-sof").then(({ ensureSofSchema }) => ensureSofSchema().catch(console.error)); import("./migrate-final-da").then(({ ensureFinalDaSchema }) => ensureFinalDaSchema().catch(console.error)); import("./migrate-voyage-expenses").then(({ ensureVoyageExpensesSchema }) => ensureVoyageExpensesSchema().catch(console.error)); import("./migrate-bunker").then(({ ensureBunkerSchema }) => ensureBunkerSchema().catch(console.error)); import("./migrate-maritime-docs").then(({ ensureMaritimeDocsSchema }) => ensureMaritimeDocsSchema().catch(console.error)); import("./migrate-reminders").then(({ ensureRemindersSchema }) => ensureRemindersSchema().catch(console.error)); import("./benchmark-calculator").then(({ ensureBenchmarkSchema, calculateBenchmarks }) => ensureBenchmarkSchema().then(() => calculateBenchmarks()).catch(console.error)); import("./migrate-email-inbound").then(({ migrateEmailInbound }) => migrateEmailInbound().catch(console.error)); import("./migrate-compliance").then(({ migrateCompliance }) => migrateCompliance().catch(console.error)); import("./cleanup-ports").then(({ cleanupInvalidPorts }) => cleanupInvalidPorts().catch(console.error)); import("./startup-checks").then(({ runStartupChecks }) => runStartupChecks().catch(console.error)); } catch (e) { console.error("Init:", e); } }, 5000);');
L.push('  setTimeout(() => { try { startCronJobs(); } catch (e) { console.log("Cron skip"); } }, 45000);');
L.push('  setTimeout(() => { try { startAISStream(); } catch (e) { console.log("AIS skip"); } }, 60000);');
L.push('  setTimeout(() => { import("./sanctions").then(({ loadSanctionsList }) => loadSanctionsList().catch(console.error)).catch(() => console.log("Sanctions skip")); }, 90000);');
L.push('  setTimeout(() => { import("./geocode-ports").then(({ geocodeMissingPorts }) => geocodeMissingPorts().catch(console.error)).catch(() => console.log("Geocode skip")); }, 120000);');
L.push('})();');

fs.writeFileSync("server/index.ts", L.join("\n"));
console.log("DONE - server/index.ts rewritten");
console.log("Boot: health->listen->routes->static->background");
console.log("Now click Publish!");
